[package]
name = "solana_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.14.14"
solana-sdk = "1.14.14"
solana-transaction-status = "1.14.14"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
anyhow = "1.0"
futures = "0.3"
log = "0.4"
env_logger = "0.9"
