AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Deploys a Solana Validator instance on r6a.8xlarge with a **single io2 EBS** for ledger & accounts.

Parameters:
  VpcId:
    Description: VPC ID for deployment.
    Type: AWS::EC2::VPC::Id
    Default: vpc-0994ff0f1275da795
  SubnetId:
    Description: Subnet ID for deployment.
    Type: AWS::EC2::Subnet::Id
    Default: subnet-011129f596ceec808
  InstanceType:
    Description: EC2 instance type.
    Type: String
    Default: r6a.8xlarge
  AMIId:
    Description: AMI ID built by Packer.
    Type: AWS::EC2::Image::Id
    Default: ami-0caebb64973074c69
  KeyName:
    Description: Name of an existing SSH KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
    Default: raydium

Resources:
  SolanaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Solana Validator instance.
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8899
          ToPort: 8899
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8900
          ToPort: 8900
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
        - IpProtocol: udp
          FromPort: 8000
          ToPort: 8020
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SolanaValidatorSG

  SolanaInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIId
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SolanaSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 1500
            VolumeType: gp3
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: SolanaValidatorInstance

Outputs:
  InstanceId:
    Description: The EC2 Instance ID.
    Value: !Ref SolanaInstance
  PublicIP:
    Description: Public IP address.
    Value: !GetAtt SolanaInstance.PublicIp
